// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXUSx35AFUYHckc-IlY2lAA8NKnH4BYyo',
    appId: '1:56169743637:web:2f4ebd7c7212e4d625551c',
    messagingSenderId: '56169743637',
    projectId: 'app-domicilios-f7ff9',
    authDomain: 'app-domicilios-f7ff9.firebaseapp.com',
    storageBucket: 'app-domicilios-f7ff9.appspot.com',
    measurementId: 'G-WZ2KM7NWHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1V_0Zr7zXVyakCvj63Y89QP5PJ3pwVqM',
    appId: '1:56169743637:android:176abe0747559b2425551c',
    messagingSenderId: '56169743637',
    projectId: 'app-domicilios-f7ff9',
    storageBucket: 'app-domicilios-f7ff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC13qZi31p8h1n8hJSJXZWbsNI-F7ZaSKc',
    appId: '1:56169743637:ios:0b06e41f1517bb0625551c',
    messagingSenderId: '56169743637',
    projectId: 'app-domicilios-f7ff9',
    storageBucket: 'app-domicilios-f7ff9.appspot.com',
    iosBundleId: 'com.example.appDomicilios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC13qZi31p8h1n8hJSJXZWbsNI-F7ZaSKc',
    appId: '1:56169743637:ios:d26e6574091af67e25551c',
    messagingSenderId: '56169743637',
    projectId: 'app-domicilios-f7ff9',
    storageBucket: 'app-domicilios-f7ff9.appspot.com',
    iosBundleId: 'com.example.appDomicilios.RunnerTests',
  );
}
